package actions

import (
	"desafio2/models"
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v5"
	"github.com/gobuffalo/x/responder"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (HelloWorld)
// DB Table: Plural (hello_worlds)
// Resource: Plural (HelloWorlds)
// Path: Plural (/hello_worlds)
// View Template Folder: Plural (/templates/hello_worlds/)

// HelloWorldsResource is the resource for the HelloWorld model
type HelloWorldsResource struct {
	buffalo.Resource
}

func HelloWorldHandler(c buffalo.Context) error {
	return c.Render(http.StatusOK, r.HTML("hello.plush.html"))
}

// List gets all HelloWorlds. This function is mapped to the path
// GET /hello_worlds
func (v HelloWorldsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	helloWorlds := &models.HelloWorlds{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all HelloWorlds from the DB
	if err := q.All(helloWorlds); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("helloWorlds", helloWorlds)
		return c.Render(http.StatusOK, r.HTML("/hello_worlds/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(helloWorlds))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(helloWorlds))
	}).Respond(c)
}

// Show gets the data for one HelloWorld. This function is mapped to
// the path GET /hello_worlds/{hello_world_id}
func (v HelloWorldsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty HelloWorld
	helloWorld := &models.HelloWorld{}

	// To find the HelloWorld the parameter hello_world_id is used.
	if err := tx.Find(helloWorld, c.Param("hello_world_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("helloWorld", helloWorld)

		return c.Render(http.StatusOK, r.HTML("/hello_worlds/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(helloWorld))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(helloWorld))
	}).Respond(c)
}

// New renders the form for creating a new HelloWorld.
// This function is mapped to the path GET /hello_worlds/new
func (v HelloWorldsResource) New(c buffalo.Context) error {
	c.Set("helloWorld", &models.HelloWorld{})

	return c.Render(http.StatusOK, r.HTML("/hello_worlds/new.plush.html"))
}

// Create adds a HelloWorld to the DB. This function is mapped to the
// path POST /hello_worlds
func (v HelloWorldsResource) Create(c buffalo.Context) error {
	// Allocate an empty HelloWorld
	helloWorld := &models.HelloWorld{}

	// Bind helloWorld to the html form elements
	if err := c.Bind(helloWorld); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(helloWorld)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("helloWorld", helloWorld)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/hello_worlds/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "helloWorld.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/hello_worlds/%v", helloWorld.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(helloWorld))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(helloWorld))
	}).Respond(c)
}

// Edit renders a edit form for a HelloWorld. This function is
// mapped to the path GET /hello_worlds/{hello_world_id}/edit
func (v HelloWorldsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty HelloWorld
	helloWorld := &models.HelloWorld{}

	if err := tx.Find(helloWorld, c.Param("hello_world_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("helloWorld", helloWorld)
	return c.Render(http.StatusOK, r.HTML("/hello_worlds/edit.plush.html"))
}

// Update changes a HelloWorld in the DB. This function is mapped to
// the path PUT /hello_worlds/{hello_world_id}
func (v HelloWorldsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty HelloWorld
	helloWorld := &models.HelloWorld{}

	if err := tx.Find(helloWorld, c.Param("hello_world_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind HelloWorld to the html form elements
	if err := c.Bind(helloWorld); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(helloWorld)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("helloWorld", helloWorld)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/hello_worlds/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "helloWorld.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/hello_worlds/%v", helloWorld.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(helloWorld))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(helloWorld))
	}).Respond(c)
}

// Destroy deletes a HelloWorld from the DB. This function is mapped
// to the path DELETE /hello_worlds/{hello_world_id}
func (v HelloWorldsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty HelloWorld
	helloWorld := &models.HelloWorld{}

	// To find the HelloWorld the parameter hello_world_id is used.
	if err := tx.Find(helloWorld, c.Param("hello_world_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(helloWorld); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "helloWorld.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/hello_worlds")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(helloWorld))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(helloWorld))
	}).Respond(c)
}
